name: Makefile CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: make install

    - name: make build
      run: make build
      
  Tests:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: Unit-Tests
      run: make unit-test
