name: Build

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install emorgency dependencies
      run: sudo apt install libayatana-appindicator3-dev

    - name: make build
      run: make build

  Tests:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make build

    - name: Unit-Tests
      run: make unit-test
